<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="DiscountCoupons.aspx.cs" Inherits="Admin_DiscountCoupons" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <table class="auto-style1">
        <tr>
            <td style="text-align: right">
    <table class="auto-style1" 
        style="border:1px solid #808080; width: 80%; margin-left: 38px;">

        <tr>
            <td  align="right">
                
                &nbsp;</td>
            <td align="left">
                &nbsp;</td>
        </tr>

        <tr>
            <td  align="right">
                
                <asp:Label ID="Label8" runat="server" Text="ItemType:"></asp:Label>
            </td>
            <td align="left">
                <asp:DropDownList ID="ddlCat" runat="server" Height="25px" Width="200px" 
                    AutoPostBack="True" onselectedindexchanged="ddlCat_SelectedIndexChanged">
                    <asp:ListItem>---Select---</asp:ListItem>
                    <asp:ListItem>Vegetables</asp:ListItem>
                    <asp:ListItem>Fruits</asp:ListItem>
                    
                </asp:DropDownList>

            </td>
        </tr>
        <tr>
            <td  align="right">
                <asp:Label ID="Label9" runat="server" Text="ItemName:"></asp:Label>
            </td>
            <td align="left">
                <asp:DropDownList ID="ddlItemName" runat="server" Height="25px" Width="200px" 
                    onselectedindexchanged="ddlItemName_SelectedIndexChanged">

                </asp:DropDownList>
            </td>
        </tr>


        <tr>
            <td style="text-align: right; width: 353px; height: 7px;">
                <asp:Label ID="Label10" runat="server" Text="Discount Persentage:"></asp:Label>
            </td>
            <td style="text-align: left; height: 7px;">
                <asp:TextBox ID="txtDisPercentage" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                <asp:Button ID="btnSubmit" runat="server" Text="Add" 
                     Height="45px" Width="100px" onclick="btnSubmit_Click" />
            </td>
        </tr>
        <tr>
            <td style="text-align: right; " colspan="2">
            <center>
                <asp:GridView ID="GridView1" runat="server" BackColor="White" 
                    BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="CoupnID"
                    AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit" 
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                    onrowupdating="GridView1_RowUpdating">
                    <Columns>
                        <asp:TemplateField HeaderText="CoupnID" Visible="false">
                            <ItemTemplate>
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("CoupnID") %>'></asp:Label>
                            </ItemTemplate>
                             <EditItemTemplate>
                                <asp:TextBox ID="txtCoupnID" runat="server" 
                                    Text='<%# Bind("CoupnID") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="CategoryName">
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("CName") %>'></asp:Label>
                            </ItemTemplate>
                           
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="ItemName">
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("ItemName") %>'></asp:Label>
                            </ItemTemplate>
                          
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DiscountPercentage">
                            <ItemTemplate>
                                <asp:Label ID="lblDiscountPercentage" runat="server" Text='<%# Bind("DiscountPercentage") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtDiscountPercentage" runat="server" 
                                    Text='<%# Bind("DiscountPercentage") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView></center>
            </td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                &nbsp;</td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                &nbsp;</td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                &nbsp;</td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                &nbsp;</td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                &nbsp;</td>
        </tr>
        <tr>
            <td style="text-align: right; width: 353px;">
                &nbsp;</td>
            <td style="text-align: left">
                &nbsp;</td>
        </tr>
        </table>
            </td>
        </tr>
        <tr>
            <td>

                &nbsp;</td>
        </tr>
    </table>


</asp:Content>

