<%@ Page Title="" Language="C#" MasterPageFile="~/UserAccount/UserMasterPage.master" AutoEventWireup="true" CodeFile="ViewCart.aspx.cs" Inherits="UserAccount_ViewCart" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <style>

p
{
    color:Red;
    
     }

</style>
<p>&nbsp;</p>

    <table class="auto-style1">
        <tr>
            <td colspan="2">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
                    BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    onrowcancelingedit="GridView1_RowCancelingEdit" EmptyDataText="Nothing added"
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing" 
                    onrowupdating="GridView1_RowUpdating" 
                    onrowdatabound="GridView1_RowDataBound">
                    <Columns>
                <asp:TemplateField HeaderText="CartId">
                            <ItemTemplate>
                                <asp:Label ID="lblCartId" runat="server" Text='<%# Bind("CartId") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="CName">
                            <ItemTemplate>
                                <asp:Label ID="lblCName" runat="server" Text='<%# Bind("CName") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="ItemName">
                            <ItemTemplate>
                                <asp:Label ID="lblItemName" runat="server" Text='<%# Bind("ItemName") %>'></asp:Label>
                            </ItemTemplate>
                            
                        </asp:TemplateField>
                      <%--  <asp:TemplateField HeaderText="AvailableQuntity">
                            <ItemTemplate>
                                <asp:Label ID="lblQuntity" runat="server" Text='<%# Bind("quantity") %>'></asp:Label>
                            </ItemTemplate>
                           
                        </asp:TemplateField>--%>
                        <asp:TemplateField HeaderText="Rate">
                            <ItemTemplate>
                                <asp:Label ID="lblRate" runat="server" Text='<%# Bind("Rate") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                          <asp:TemplateField HeaderText="DiscountRate">
                            <ItemTemplate>
                                <asp:Label ID="lblDiscountRate" runat="server" Text='<%# Bind("DiscountPercentage") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                       <%--  <asp:TemplateField HeaderText="DiscountAmount">
                            <ItemTemplate>
                                <asp:Label ID="DiscountAmount" runat="server" Text='<%# Bind("DiscountAmount") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>--%>

                        <asp:TemplateField HeaderText="NoOfItems">
                            <ItemTemplate>
                                <asp:Label ID="lblNoOfItems" runat="server" Text='<%# Bind("NoOfItems") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtNoOfItems" runat="server" Text='<%# Bind("NoOfItems") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="TotalAmount">
                            <ItemTemplate>
                                <asp:Label ID="lblNetAmount" runat="server" Text='<%# Bind("NetAmount") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        
                        <asp:TemplateField HeaderText="ItemPath" HeaderStyle-Width="100px">
            <ItemTemplate>
                <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("ItemPath") %>'
                     Height="80px" Width="100px" />
            </ItemTemplate>
            
<HeaderStyle Width="100px"></HeaderStyle>
            
        </asp:TemplateField>
                        <asp:TemplateField HeaderText="ItemId" Visible="False">
                            <ItemTemplate>
                                <asp:Label ID="lblItemId" runat="server" Text='<%# Bind("ItemId") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td style="text-align: right">
                <asp:Label ID="Label1" runat="server" Text="Net Amount:"></asp:Label>
            </td>
            <td>
                <asp:TextBox ID="txtNetAmonut" runat="server" Height="25px" Width="200px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td style="text-align: right">
                <asp:Label ID="Label10" runat="server" Text="Service Amount:"></asp:Label>
            </td>
            <td>
                <asp:DropDownList ID="DropDownList1" runat="server">
                    <asp:ListItem>--Select--</asp:ListItem>
                    <asp:ListItem>Free</asp:ListItem>
                    <asp:ListItem>50</asp:ListItem>
                </asp:DropDownList>
            </td>
        </tr>
        <tr>
            <td style="text-align: right">
                <asp:Label ID="Label8" runat="server" Text="CardType:"></asp:Label>
            </td>
            <td>
                <asp:RadioButtonList ID="RadioButtonList1" runat="server" 
                    RepeatDirection="Horizontal">
                    <asp:ListItem>CreditCard</asp:ListItem>
                    <asp:ListItem>DebitCard</asp:ListItem>
                </asp:RadioButtonList>
            </td>
        </tr>
        <tr>
            <td style="text-align: right; height: 26px;">
                <asp:Label ID="Label2" runat="server" Text="AccountNo:"></asp:Label>
            </td>
            <td style="height: 26px">
                <asp:TextBox ID="txtAccount" runat="server" Height="25px" Width="200px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td style="text-align: right; height: 26px;">
                <asp:Label ID="Label9" runat="server" Text="Booking Date:"></asp:Label>
            </td>
            <td style="height: 26px">
                <asp:TextBox ID="TextBox1" runat="server" Height="25px" Width="200px"></asp:TextBox>
                <asp:CalendarExtender ID="TextBox1_CalendarExtender" runat="server" 
                    Enabled="True" Format="dd-MM-yyyy" TargetControlID="TextBox1" 
                    PopupPosition="Right">
                </asp:CalendarExtender>
            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="lblCartId" runat="server" Visible="False"></asp:Label>
                <asp:Label ID="lblRes" runat="server" Visible="False"></asp:Label>
            </td>
            <td>
                <asp:Button ID="Button1" runat="server" Height="45px" Text="Submit" 
                    Width="100px" onclick="Button1_Click" />
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
</asp:Content>

